-i /home/tahmeed/Desktop/modifications/UVM_PRACTICE/axi_uart_uvm_tb/include
/home/tahmeed/Desktop/modifications/UVM_PRACTICE/axi_uart_uvm_tb/src/apb_pkg.sv
/home/tahmeed/Desktop/modifications/UVM_PRACTICE/axi_uart_uvm_tb/src/cf_math_pkg.sv
/home/tahmeed/Desktop/modifications/UVM_PRACTICE/axi_uart_uvm_tb/src/axi_pkg.sv
/home/tahmeed/Desktop/modifications/UVM_PRACTICE/axi_uart_uvm_tb/src/base_pkg.sv
/home/tahmeed/Desktop/modifications/UVM_PRACTICE/axi_uart_uvm_tb/interface/axi_intf.sv
/home/tahmeed/Desktop/modifications/UVM_PRACTICE/axi_uart_uvm_tb/interface/uart_intf.sv
/home/tahmeed/Desktop/modifications/UVM_PRACTICE/axi_uart_uvm_tb/interface/reset_intf.sv
/home/tahmeed/Desktop/modifications/UVM_PRACTICE/axi_uart_uvm_tb/src/gray_to_bin.sv
/home/tahmeed/Desktop/modifications/UVM_PRACTICE/axi_uart_uvm_tb/src/bin_to_gray.sv
/home/tahmeed/Desktop/modifications/UVM_PRACTICE/axi_uart_uvm_tb/src/lzc.sv
/home/tahmeed/Desktop/modifications/UVM_PRACTICE/axi_uart_uvm_tb/src/fifo_v3.sv
/home/tahmeed/Desktop/modifications/UVM_PRACTICE/axi_uart_uvm_tb/src/delta_counter.sv
/home/tahmeed/Desktop/modifications/UVM_PRACTICE/axi_uart_uvm_tb/src/uart_reg_if.sv
/home/tahmeed/Desktop/modifications/UVM_PRACTICE/axi_uart_uvm_tb/src/axi_demux.sv
/home/tahmeed/Desktop/modifications/UVM_PRACTICE/axi_uart_uvm_tb/src/register_dual_flop.sv
/home/tahmeed/Desktop/modifications/UVM_PRACTICE/axi_uart_uvm_tb/src/mux.sv
/home/tahmeed/Desktop/modifications/UVM_PRACTICE/axi_uart_uvm_tb/src/uart_top.sv
/home/tahmeed/Desktop/modifications/UVM_PRACTICE/axi_uart_uvm_tb/src/axi_demux_simple.sv
/home/tahmeed/Desktop/modifications/UVM_PRACTICE/axi_uart_uvm_tb/src/decoder.sv
/home/tahmeed/Desktop/modifications/UVM_PRACTICE/axi_uart_uvm_tb/src/rr_arb_tree.sv
/home/tahmeed/Desktop/modifications/UVM_PRACTICE/axi_uart_uvm_tb/src/axi_demux_id_counters.sv
/home/tahmeed/Desktop/modifications/UVM_PRACTICE/axi_uart_uvm_tb/src/axi_burst_splitter_counters.sv
/home/tahmeed/Desktop/modifications/UVM_PRACTICE/axi_uart_uvm_tb/src/dff.sv
/home/tahmeed/Desktop/modifications/UVM_PRACTICE/axi_uart_uvm_tb/src/axi_to_axi_lite.sv
/home/tahmeed/Desktop/modifications/UVM_PRACTICE/axi_uart_uvm_tb/src/err_gen.sv
/home/tahmeed/Desktop/modifications/UVM_PRACTICE/axi_uart_uvm_tb/src/axi_fifo.sv
/home/tahmeed/Desktop/modifications/UVM_PRACTICE/axi_uart_uvm_tb/src/axi_to_simple_if.sv
/home/tahmeed/Desktop/modifications/UVM_PRACTICE/axi_uart_uvm_tb/src/edge_detector.sv
/home/tahmeed/Desktop/modifications/UVM_PRACTICE/axi_uart_uvm_tb/src/counter.sv
/home/tahmeed/Desktop/modifications/UVM_PRACTICE/axi_uart_uvm_tb/src/demux.sv
/home/tahmeed/Desktop/modifications/UVM_PRACTICE/axi_uart_uvm_tb/src/mem.sv
/home/tahmeed/Desktop/modifications/UVM_PRACTICE/axi_uart_uvm_tb/src/onehot_to_bin.sv
/home/tahmeed/Desktop/modifications/UVM_PRACTICE/axi_uart_uvm_tb/src/spill_register_flushable.sv
/home/tahmeed/Desktop/modifications/UVM_PRACTICE/axi_uart_uvm_tb/src/register.sv
/home/tahmeed/Desktop/modifications/UVM_PRACTICE/axi_uart_uvm_tb/src/uart_tx.sv
/home/tahmeed/Desktop/modifications/UVM_PRACTICE/axi_uart_uvm_tb/src/stream_register.sv
/home/tahmeed/Desktop/modifications/UVM_PRACTICE/axi_uart_uvm_tb/src/axi_atop_filter.sv
/home/tahmeed/Desktop/modifications/UVM_PRACTICE/axi_uart_uvm_tb/src/uart_rx.sv
/home/tahmeed/Desktop/modifications/UVM_PRACTICE/axi_uart_uvm_tb/src/axi_burst_splitter.sv
/home/tahmeed/Desktop/modifications/UVM_PRACTICE/axi_uart_uvm_tb/src/axi_to_axi_lite_id_reflect.sv
/home/tahmeed/Desktop/modifications/UVM_PRACTICE/axi_uart_uvm_tb/src/id_queue.sv
/home/tahmeed/Desktop/modifications/UVM_PRACTICE/axi_uart_uvm_tb/src/axi_err_slv.sv
/home/tahmeed/Desktop/modifications/UVM_PRACTICE/axi_uart_uvm_tb/src/clk_div.sv
/home/tahmeed/Desktop/modifications/UVM_PRACTICE/axi_uart_uvm_tb/src/spill_register.sv
/home/tahmeed/Desktop/modifications/UVM_PRACTICE/axi_uart_uvm_tb/src/axi_burst_splitter_ax_chan.sv
/home/tahmeed/Desktop/modifications/UVM_PRACTICE/axi_uart_uvm_tb/src/cdc_fifo.sv
/home/tahmeed/Desktop/modifications/UVM_PRACTICE/axi_uart_uvm_tb/test/tb/tb_top.sv
/home/tahmeed/Desktop/modifications/UVM_PRACTICE/axi_uart_uvm_tb/test/uvm/seq_items/dut_seq_item.sv
/home/tahmeed/Desktop/modifications/UVM_PRACTICE/axi_uart_uvm_tb/test/uvm/sequences/uart_config_sequence.sv
/home/tahmeed/Desktop/modifications/UVM_PRACTICE/axi_uart_uvm_tb/test/uvm/components/axi/axi_driver.sv
/home/tahmeed/Desktop/modifications/UVM_PRACTICE/axi_uart_uvm_tb/test/uvm/components/axi/axi_monitor.sv
/home/tahmeed/Desktop/modifications/UVM_PRACTICE/axi_uart_uvm_tb/test/uvm/components/axi/axi_sequencer.sv
/home/tahmeed/Desktop/modifications/UVM_PRACTICE/axi_uart_uvm_tb/test/uvm/components/axi/axi_scoreboard.sv
/home/tahmeed/Desktop/modifications/UVM_PRACTICE/axi_uart_uvm_tb/test/uvm/components/axi/axi_agent.sv
/home/tahmeed/Desktop/modifications/UVM_PRACTICE/axi_uart_uvm_tb/test/uvm/components/axi/axi_env.sv
/home/tahmeed/Desktop/modifications/UVM_PRACTICE/axi_uart_uvm_tb/test/uvm/testcases/base_test.sv
/home/tahmeed/Desktop/modifications/UVM_PRACTICE/axi_uart_uvm_tb/test/uvm/axi_tb_top.sv
